### ISSUE TITLE
[Feature request]: 是否可以加入这个项目的解码优化，目前米系老电视的延迟太高了

### ISSUE THREAD

**Issue by Zyeus** [ClassicOldSong/moonlight-android#11]
### Is your feature request related to a problem? Please describe.

https://github.com/rexq57/moonlight-android/tree/master

### Describe the solution you'd like

红米 X65 2020版，视频解码延迟60ms以上，影响使用

### Describe alternatives you've considered

https://github.com/rexq57/moonlight-android/tree/master
这个项目好久没有维护，但看着是做了解码的优化
https://mp.weixin.qq.com/s?src=11&timestamp=1724984689&ver=5475&signature=4GYnHRJvi-G-5-5X4Has9IQ*omHcgLyHQsa9ULjnS4KJcxKOMDBUPMjGwhuYlFiaB2EPMhaG1Zhy4rj5*xX93LYY0YHxqer4umXrnxQs15cTYqe2XovbGR0uK*7Kl7Pb&new=1

**Comment by ClassicOldSong** [comment]
你有确认过这个版本延迟确定更低吗？低多少？

**Comment by ClassicOldSong** [comment]
大致（90%仔细）看了一下，意义不大。

导致电视延迟大的可能性是MTK的锅，Moonlight主项目那边也有一个[关于MTK的很长的讨论](https://github.com/moonlight-stream/moonlight-android/issues/1241)，这个项目降低延迟最主要的操作是设置了几个非主流解码器的低延迟flag，而很遗憾里面不包含MTK。另外关于流畅度的部分也在新的Moonlight里基本由Frame Pacing选项提供了，所以没有合并的必要。

**Comment by XT-Martinez** [comment]
Hi, I experienced the same high decoding latency using Mediatek SoC but I found out that tapping repeatedly lowers the decoding time significantly (see my comment in https://github.com/moonlight-stream/moonlight-android/issues/1241#issuecomment-2510486938).

I tried to use the Galileo G8's G mode that emulates touch input and I can get a steady low decode latency when rapid firing.

I was wondering if you can implement something like a dirty hack that sends fake touch input repeatedly

**Comment by ClassicOldSong** [comment]
Emulating input would require ADB permission or a separated physical device, in this case G8/G8+ might be a relatively good choice though...

Or perhaps you can implement an emulated touchscreen using an Arduino or something similar for this purpose specifically.
