### ISSUE TITLE
[Feature request]: A more functional Esc key and mouse mapping

### ISSUE THREAD

**Issue by ShorTerrMood** [ClassicOldSong/moonlight-android#16]
### Is your feature request related to a problem? Please describe.

When I stream on my tablet, to simulate pressing the Esc key, I have to go through the "Advanced Menu" and select the "Send Special Keys" option. However, if I press the Esc key directly on the tablet's keyboard (the official keyboard for the Xiaomi Pad 6 Max), it triggers the system's "Back" function. 
Also, I have a small request regarding mouse usage. When using the mouse, the system cursor appears as well (in the ToDesk software, this does not happen). 

### Describe the solution you'd like

In previous updates, I noticed that you can remap the Esc key to the Meta key. Is there a way to create an option so that the Esc key can function normally?
Is there a way to make mouse operations directly adhere to the software without showing the system cursor?

### Describe alternatives you've considered

Referring to your previous binding of the Esc key, you can prioritize the Esc key's function as the Esc key within the software, while disabling its role as the system "Back" button when used in the software.

**Comment by ClassicOldSong** [comment]
You can try map your keys manually using a different keyboard layout.

You can refer to this repo as a starting point: https://github.com/ClassicOldSong/OnePlusPadProKeyboardLayout

**Comment by ClassicOldSong** [comment]
For mouse, please disable "Optimize for remote desktop usage" in the settings. Normally mouse should be captured.

**Comment by ShorTerrMood** [comment]
Hello, regarding the mouse issue, I have found a solution. It was caused by incorrect operation on my part. As for the keyboard mapping issue, after using the keyboard layout, I still cannot use the Esc key correctly (I think this might be related to the logic of the Xiaomi tablet keyboard, but I’m not sure how the Todesk software handles it). Thank you for your explanation!

**Comment by ShorTerrMood** [comment]
Hello! I found a solution to the problem! In the Settings → Accessibility section, enabling the Moonlight physical keyboard option allows for perfect use (although the Meta key on the keyboard still brings up the toolbar at the bottom, at least the Win key now works properly). Thank you again for your patient explanation!

**Comment by ClassicOldSong** [comment]
Glad your problems are solved!

**Comment by mesquitafmr** [comment]
> Hello! I found a solution to the problem! In the Settings → Accessibility section, enabling the Moonlight physical keyboard option allows for perfect use (although the Meta key on the keyboard still brings up the toolbar at the bottom, at least the Win key now works properly). Thank you again for your patient explanation!

Can say it fixes the external keyboard input problems on Samsung's One UI 8 devices, which were introduced with this new android version.
