### ISSUE TITLE
[Issue]: Direct touch triggers click event on old mouse position

### ISSUE THREAD

**Issue by Sa1ev** [ClassicOldSong/moonlight-android#18]
### Describe the bug

https://www.reddit.com/r/MoonlightStreaming/comments/1ciqbt8/bugandroid_direct_touch_triggers_click_event_on/ 
I has similar issue when you select Mluti touch (guess typo in resources), but i have no idea if you can reproduce it. I checked logs, there is correct event sending sequence on each click (sendMousePosition==2 -> sendMousePosition==4 -> sendMousePosition==5), but my guess is that on receiveng side in handles click event before mouse position change event. For my build I simply put a 50ms delay before sending MoonBridge.sendMouseButton(MouseButtonPacket.RELEASE_EVENT, mouseButton) and MoonBridge.sendMouseButton(MouseButtonPacket.PRESS_EVENT, mouseButton) to let GeForce handle postion change and it solves the issue, but maybe you could find a better solution. 

### Steps to reproduce

select Mluti touch and just try to click or drag anything on screen

### Other Moonlight clients

None

### Moonlight adjusted settings

None

### Moonlight default settings

Yes

### Gamepad-related connection issue

No

### Gamepad-related input issue

No

### Gamepad-related streaming issue

No

### Android version

14

### Device model

Galaxy Tab S9 Ultra

### Server PC OS version

Windows 11, version 23H2

**Comment by ClassicOldSong** [comment]
Cannot reproduce on my devices, might this be a Samsung specific issue since DeX might introduce some variances.

Can you try Apollo and see if this issue presists?

**Comment by Sa1ev** [comment]
Well, I can't reproduce it with Apollo + non-modified Artemis; it's probably a problem on GeForce side then.

**Comment by ClassicOldSong** [comment]
GFE is no longer recommended as Nvidia has abandoned the project. Input batching/dropping is a known issue there.
