### ISSUE TITLE
[Issue]: Typo in Settings for "Multi Touch"

### ISSUE THREAD

**Issue by JoeKoh27** [ClassicOldSong/moonlight-android#19]
### Describe the bug

There is a typo in the Touch settings, instead of "Multi touch" it is spelled as "Mluti touch"

### Steps to reproduce

At the Artemis home screen, click the top left settings icon. Scroll down to Input Settings and click "Touchscreen Mode". The first option is spelled as "Mluti Touch"
![IMG_20240923_203557](https://github.com/user-attachments/assets/48e294ec-6129-4a8f-ad39-a5299d02984a)

### Other Moonlight clients

PC

### Moonlight adjusted settings

No

### Moonlight default settings

Yes

### Gamepad-related connection issue

No

### Gamepad-related input issue

Yes

### Gamepad-related streaming issue

Yes

### Android version

Android 11

### Device model

Xiaomi Mi 9

### Server PC OS version

Windows 11 23H2

### Server PC GeForce Experience version

3.28.0.417

### Server PC Nvidia GPU driver version

561.09

### Server PC antivirus and firewall software

Windows Defender 

### Screenshots

![IMG_20240923_203557](https://github.com/user-attachments/assets/1b59b183-465b-473d-985c-33e81151d6c1)

**Comment by ClassicOldSong** [comment]
Fixed in https://github.com/ClassicOldSong/moonlight-android/releases/tag/v12.1-artemis-240924
