### ISSUE TITLE
Trackpad Two Finger Scroll Support

### ISSUE THREAD

**Issue by ClassicOldSong** [ClassicOldSong/moonlight-android#2]
### Discussed in https://github.com/ClassicOldSong/moonlight-android/discussions/1

<div type='discussions-op-text'>

<sup>Originally posted by **emreozcelik** July 30, 2024</sup>
I couldn't get the trackpad scrolling to work on Tab S9. I also couldn't find an option for it in the settings. Am I missing something, or is this issue specific to the Tab S9?</div>

**Comment by ClassicOldSong** [comment]
@emreozcelik Does tap as click work on your tablet?

Also can you check if Trackpad(Natural) mode works on your touch screen?

Trackpad support is enabled by default and there's no option for it.

Maybe you can try disabling "Remote desktop mouse mode" and see if it works.

**Comment by emreozcelik** [comment]
Tap to click works as intended. For example, tapping on an icon selects it.

Two-finger scroll on the touchscreen with trackpad (Natural) mode works correctly.

It was disabled by default, but I tested it with both enabled and disabled settings to be sure. Unfortunately, this did not resolve the issue.

To clarify, there was no Bluetooth device attached to the device - just the magnetic keyboard.

**Comment by ClassicOldSong** [comment]
Got it. I don't have a Samsung tablet to test with, I'll ask my firend who has a S7 for some help with testing but it may take some time.

**Comment by ClassicOldSong** [comment]
https://github.com/ClassicOldSong/moonlight-android/releases/tag/v12.1-noir-240802

Can you give this version a try? Double tap dragging is not possible with DeX, and you have to tap two fingers to use right click. Scrolling should work out of the box.

**Comment by emreozcelik** [comment]
Thank you for the update. The issue has been resolved, and everything is working perfectly now. 🙂

**Comment by ClassicOldSong** [comment]
Glad it works!
