### ISSUE TITLE
[Issue]:"Back button as meta key" not working since version 20240924

### ISSUE THREAD

**Issue by ghost** [ClassicOldSong/moonlight-android#20]
### Describe the bug

Hi. I'm using a Logitech K380 and I have a problem - Meta (Win) key input no longer works after I updated the app.
So I downgraded to 20240911 and it works fine without problems.
The host PC uses Apollo v0.2.3-alpha.1.

### Steps to reproduce

Press the back button on K380 as shown in the picture below.
From this page, it returns only "0" instead of "91"
https://uiwjs.github.io/keycode-info/

### Other Moonlight clients

None

### Moonlight adjusted settings

None

### Moonlight default settings

Yes

### Gamepad-related connection issue

No

### Gamepad-related input issue

No

### Gamepad-related streaming issue

No

### Android version

Android 14

### Device model

Keyboard is Logitech K380 (not K380S)

### Server PC OS version

Windows 10 21H2

### Screenshots

![k380](https://github.com/user-attachments/assets/8c634cf5-0c18-4b82-a24a-2022de233557)

**Comment by ClassicOldSong** [comment]
Luckily I have a K380 on hand and it's confirmed working with the fix, will rerease later

**Comment by ClassicOldSong** [comment]
Released: https://github.com/ClassicOldSong/moonlight-android/releases/tag/v12.1-artemis-240925

**Comment by ghost** [comment]
Thank you. Just updated and works as expected.
