### ISSUE TITLE
[Feature request]: 指定使用的解码器

### ISSUE THREAD

**Issue by nothingshiru** [ClassicOldSong/moonlight-android#25]
### Is your feature request related to a problem? Please describe.

同样设置2560x1440@120，h264编码，骁龙870平板使用的解码器是OMX.qcom.video.decoder.avc，解码延迟约6秒；骁龙7+Gen3手机使用的解码器是c2.qti.avc.decoder.low_latency，解码延迟约16秒，比前者高了差不多2倍。

我之前使用scrcpy投屏平板到电脑时试了不同的编码器，也是OMX.qcom开头的编码器延迟最低。似乎OMX.qcom开头的是硬件解码器，c2.qti开头的是软件编解码器。

### Describe the solution you'd like

希望能够设置指定的解码器

### Describe alternatives you've considered

None

### Screenshots

![Screenshot_20240928_115233](https://github.com/user-attachments/assets/b6c47816-30ce-4241-a27b-b890069cf629)
![Screenshot_2024-09-28-11-56-26-82_db88886dd2f8c743276d69c47cc9553b](https://github.com/user-attachments/assets/f21a9970-b2c1-4a59-a044-d7da18078c4f)

**Comment by ClassicOldSong** [comment]
870是旗舰CPU，7G3是二线，产品定位被拿捏的死死的。。。
7G3我正好有，8G3我也有，新的low latency解码器已经是这个CPU能做到最好的了。。。
而且8G3的H264/H265解码延迟据传也比8G1要高

![image](https://github.com/user-attachments/assets/70d77da1-0c6b-43df-877e-a7378044d195)

![image](https://github.com/user-attachments/assets/e60f1628-69ab-4d04-91c8-bc83f6c4c32f)

这是从7G3设备上截的图，low_latency解码器也是硬件加速的，而且low_latency本身的含义就是“低延迟”

注意一下，这边OMX的就是c2的别名，两者没有差别

**Comment by nothingshiru** [comment]
意思是7+Gen3没有OMX.qcom的解码器？😧

**Comment by ClassicOldSong** [comment]
有，但就是c2的别名

**Comment by nothingshiru** [comment]
所以现在已经是自动选择最好的解码器了，对吧？

**Comment by ClassicOldSong** [comment]
对的
