### ISSUE TITLE
[Feature request]: Game and Controller Detection for OSC

### ISSUE THREAD

**Issue by Stoutscientist** [ClassicOldSong/moonlight-android#27]
### Is your feature request related to a problem? Please describe.

I don't like having the on screen controls enabled all the time and I'm lazy lol

### Describe the solution you'd like

It'd be awesome if you could type in a list of exe's on the server side and then on the client if it detected any of those it'd automatically turn on/off on screen controls, and it would be cool if they would turn off if a controller is plugged in.

### Describe alternatives you've considered

.

**Comment by SagarChandra07** [comment]
maybe this will help

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive password: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by ClassicOldSong** [comment]
It's already convenient enough that you can toggle OSC from back menu. Don't be that lazy 😂
