### ISSUE TITLE
[Feature request]: 触摸板双指缩放

### ISSUE THREAD

**Issue by C0deH0st** [ClassicOldSong/moonlight-android#28]
非常喜欢作者的版本，我在使用vivopad3pro的键盘触摸板，因为系统bug，怎么旋转键盘触摸板都是旋转90度的。于是我只能修改代码手动编译一个能用的版本，主要是反转触摸板的xy轴：

TrackpadContext.java
`

            int deltaX = absDeltaY; // 交换
            int deltaY = absDeltaX; // 交换

            // Fix up the signs
            if (eventY < lastTouchY) {
                deltaX = -absDeltaY; // 对 deltaX 取反
            }
            if (eventX > lastTouchX) {
                deltaY = -absDeltaX; 
            }

            lastTouchX = eventX;
            lastTouchY = eventY;

            // 确保 deltaX 和 deltaY 交换后用于发送时的正确性
            if (pointerCount == 1) {
                // 单指滑动直接传递鼠标移动
                conn.sendMouseMove((short) deltaX, (short) deltaY); // 交换
            } else if (pointerCount == 2 && actionIndex == 1) {
                checkForConfirmedScroll();
                if (confirmedScroll) {
                    // 判断主方向
                    boolean isHorizontal = absDeltaY > absDeltaX; // 交换

                    if (isHorizontal) {
                        // 主要为水平方向滚动
                        conn.sendMouseHighResHScroll((short)(-deltaX * SCROLL_SPEED_FACTOR_X)); // 水平滚动
                        // 若垂直滑动也比较显著，可以同时发送垂直滚动
                        if (absDeltaX * 1.05 > absDeltaY) { // 交换
                            conn.sendMouseHighResScroll((short)(deltaY * SCROLL_SPEED_FACTOR_Y)); // 交换
                        }
                    } else {
                        // 主要为垂直方向滚动
                        conn.sendMouseHighResScroll((short)(deltaY * SCROLL_SPEED_FACTOR_Y)); // 交换
                        // 若水平滑动也比较显著，可以同时发送水平滚动
                        if (absDeltaY * 1.05 >= absDeltaX) { // 交换
                            conn.sendMouseHighResHScroll((short)(-deltaX * SCROLL_SPEED_FACTOR_X)); // 水平滚动
                        }
                    }
                }
            }
        }

        return true;
    }
`

另外我发现在双指滚动的过程，可以同时发送垂直和水平滚动，可以让体验更丝滑一些
由于这是一些小众bug，我觉得这也没法合并到代码中。。如果可以的话能否添加一个触摸板旋转的选项，谢谢！
请问作者方便请问能否适配一下trackpad的双指缩放操作，万分感谢！

**Comment by ClassicOldSong** [comment]
同时发送横纵滚动是已经实现了的，这些注释是AI添加的吧

我稍微clip一些的原因是纵向滚动的时候其实手并不是标准垂直移动的，这时候把偏移出来的一点横向移动也发过去的话会觉得很奇怪，所以写成了目前这样

你要是早两分钟开issue也许强制旋转坐标刚刚发布的这个版本就有了😂

**Comment by ClassicOldSong** [comment]
触摸板缩放不太好做，虽然可以通过发送键盘组合键来模拟，但总归不是很自然

而Windows模拟触摸板非常麻烦，短期内不会考虑实现
