### ISSUE TITLE
[Feature request]: Stream Connected Notification on Primary Device

### ISSUE THREAD

**Issue by sickypedia** [ClassicOldSong/moonlight-android#29]
### Is your feature request related to a problem? Please describe.

Since Apollo supports marks the first connected device as primary (and grants all permissions), can the primary client (or one client specifically selected in Apollo) display a persistent notification if a stream was initiated from any of the other paired devices? 

### Describe the solution you'd like

Sharing use-case:
I am sharing my gaming laptop with a relative who remotely gamestreams (via tailscale) and a notification on my primary android client that a gamestream session is ongoing would be helpful in not interrupting the current session. This may more be a feature to implement on Apollo side, but raising here as the notification is preferred on the primary client (which happens to be my phone with Artemis).

### Describe alternatives you've considered

Info above

**Comment by ClassicOldSong** [comment]
You can disable the "Launch Apps" permission for other clients, and Apollo will display a notification for a new client joining.

This is an already implemented feature.

**Comment by sickypedia** [comment]
Thanks for the reply. While there's a notification on the Windows PC when a client joins, there's nothing on Artemis (first device), which is not in an active session.

**Comment by ClassicOldSong** [comment]
That will introduce a whole bunch of things that are not easily doable in a standalone self-hosting server, including message pushing, account management and a lot more. Maybe I can add webhooks in the future, but built-in push notifications won't be added in the forseeable future.
