### ISSUE TITLE
[Feature Request] Show Network Usage in full Performance Stats

### ISSUE THREAD

**Issue by haldi4803** [ClassicOldSong/moonlight-android#30]
Hello,

The current Performance Stats show everything you need to know.
Network related latency and dropped frames.
![1728128177998](https://github.com/user-attachments/assets/d5b984a7-fb55-4530-8a2d-a90f83c3eca6)

But it would be pretty cool to also show current bandwith usage. So you know how much or your assigned Bandwith is actually used.

**Comment by ClassicOldSong** [comment]
Checkout lite mode in [Artemis](https://github.com/ClassicOldSong/moonlight-android) settings

**Comment by haldi4803** [comment]
Yes exactly that one!
IMHO that should also be visible in the full statistics
![Screenshot_2024-10-05-16-33-44-36_db88886dd2f8c743276d69c47cc9553b_1](https://github.com/user-attachments/assets/55e3120e-a296-4cfe-b593-3026560d7944)
