### ISSUE TITLE
[Feature request]: 串流的时候如何用手柄按出快捷菜单

### ISSUE THREAD

**Issue by coro531** [ClassicOldSong/moonlight-android#33]
### Is your feature request related to a problem? Please describe.

阿西西版本moonlight可以手柄长按start调出快捷菜单，想问下黑月版能不能用手柄调出快捷菜单，因为是在电视上串流，没办法左滑返回调出快捷菜单，希望可以用手柄按出

![QQ截图20241011104957](https://github.com/user-attachments/assets/9664c8be-a043-4572-87ff-96987e98cfe7)

### Describe the solution you'd like

目前长按start键是开启鼠标模式，是否能够有个选项可以选择长按start调出快捷菜单

### Describe alternatives you've considered

目前长按start键是开启鼠标模式，是否能够有个选项可以选择长按start调出快捷菜单

### Screenshots

![QQ截图20241011104957](https://github.com/user-attachments/assets/e5fe56c0-012f-424d-a4a5-abf5e85c215a)

**Comment by ClassicOldSong** [comment]
短按一下start然后长按再松开即可
