### ISSUE TITLE
请教下如何在串流的时候用手柄按出快捷菜单

### ISSUE THREAD

**Issue by coro531** [ClassicOldSong/moonlight-android#35]
阿西西版本可以手柄长按start调出快捷菜单，想问下黑月版能不能用手柄调出快捷菜单，因为是在电视上串流，没办法按返回键调出快捷菜单，希望可以用手柄按出

![QQ截图20241011104957](https://github.com/user-attachments/assets/05ead50d-2887-4239-a776-ef2dbdc6b41c)

**Comment by ClassicOldSong** [comment]
短按一下start然后长按再松开即可

**Comment by coro531** [comment]
谢谢，按你说的短按再长按，短按后的长按要按得很快，节奏不对不太容易按出来，能否考虑下长按手柄一个键就调出快捷菜单，start或select都可以，或者组合键比如同时按下start+select就可以弹出快捷菜单，这样在电视上操作较方便
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            Yukino ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2024年10月11日 12:28
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [ClassicOldSong/moonlight-android] 请教下如何在串流的时候用手柄按出快捷菜单 (Issue #35)
        
      
    
  

短按一下start然后长按再松开即可

**Comment by ClassicOldSong** [comment]
不考虑，各个应用都想占用某种组合键或者长按操作，很容易冲突然后又要再来寻找新的组合键方案，目前这样误触几率很低，因此不再考虑别的方式。
