### ISSUE TITLE
Higher packet loss than Moonlight android vanilla

### ISSUE THREAD

**Issue by Marocco2** [ClassicOldSong/moonlight-android#39]
### Describe the bug

Comparing the same stream settings in the same network environment, Artemis has a much worse image quality due to higher packet loss (up to 20%) than Moonlight vanilla android client (close to 0%).
Both clients have the same settings. I've tried also native display but same issue appear

### Steps to reproduce

- Launch a stream with Artemis
- Look into network stats overlay
- Redo the same with vanilla client

### Other Moonlight clients

None

### Moonlight adjusted settings

Yes

### Moonlight adjusted settings (please complete the following information)

- HEVC
- Native screen resolution 
- Forced virtual display 
- 120 FPS 
- Don't force Xbox controller
- No gyro
- Stats overlay

### Moonlight default settings

Yes

### Gamepad-related connection issue

No

### Gamepad-related input issue

Yes

### Gamepad-related streaming issue

Yes

### Android version

Android 14 (GrapheneOS)

### Device model

Pixel 8 Pro 

### Server PC OS version

Windows 11 23H2

**Comment by ClassicOldSong** [comment]
It couldn't be true if configs are all the same. Have you checked your bitrate and decoder configuration?

**Comment by Marocco2** [comment]
> It couldn't be true if configs are all the same. Have you checked your bitrate and decoder configuration?

Decoder is the same for both (HEVC)
Both were 20Mbps. I also tried vanilla to 61Mbps and even there packet losses aren't happening as much as Artemis does.
I'll check again in a few hours (in a different environment unfortunately) but I found it consistent on multiple retries

**Comment by ClassicOldSong** [comment]
Can you try to confirm it on a different devices? I don't have any Pixel devices so I can't check if it's related to GrapheneOS. Theoratically this shouldn't happen since streaming part there're no differences between Artemis and OG Moonlight, and I have not met any situations that Artemis performs worse than OG Moonlight on all Android devices I have.

**Comment by Marocco2** [comment]
> Can you try to confirm it on a different devices? I don't have any Pixel devices so I can't check if it's related to GrapheneOS. Theoratically this shouldn't happen since streaming part there're no differences between Artemis and OG Moonlight, and I have not met any situations that Artemis performs worse than OG Moonlight on all Android devices I have.

I'll check on a Fire TV 4k stick in a few hours (still HEVC).
Yeah, I am surprised too to find this thing happening. I'll check if changing touch screen modes would help me to solve these packet losses

**Comment by ClassicOldSong** [comment]
Any updates?

**Comment by Marocco2** [comment]
> Any updates?

I can't get to replicate this issue anymore with more devices I've tried.
I can safely close this issue
