### ISSUE TITLE
Custom refresh rate decoupled from FPS stream

### ISSUE THREAD

**Issue by Marocco2** [ClassicOldSong/moonlight-android#40]
### Is your feature request related to a problem? Please describe.

https://youtu.be/msOWcvoIC8M?t=337

Overall display latency can be lowered if (virtual) display monitor can be set at higher refresh rates than matching FPS/RF would provide.
Furthermore, certain hw decoders are incapable of decoding at higher FPS streams than detailed specs, resulting in a much worse decoding performance and latency for lower end devices (like Fire stick 4K)

### Describe the solution you'd like

I'd like a setting option that multiplies requested FPS stream (ranging from x1 to x4 with default at x2).
Tearing shouldn't be a problem as they would be integer numbers and a better v-sync presentation 

### Describe alternatives you've considered

Other workarounds include manually go to Windows settings and change every time displayed refresh rate.

**Comment by ClassicOldSong** [comment]
It can only be lowered if the actual renderer that render on the screen you're viewing renders at a higher frequency. In short, when the screen is displayed ad 60hz, both the stream and view updates should be requested at 120hz  for a lower latency. Refresh rate multiplication makes no sense in this situation if the actual refresh rate is capped by the display media.

The even shorter answer is, avoid devices that have no way to turn VRR off/have low decoding capability in the future.
