### ISSUE TITLE
[Issue]: 天玑 9400 会突然出现丢包

### ISSUE THREAD

**Issue by beermedlar** [ClassicOldSong/moonlight-android#47]
### Describe the bug

在使用天玑9400在游玩时会不时出现丢包卡顿，在同等网络条件下的高通870运行正常

### Steps to reproduce

无

### Other Moonlight clients

None

### Moonlight adjusted settings

None

### Moonlight default settings

Yes

### Gamepad-related connection issue

Yes

### Gamepad-related input issue

Yes

### Gamepad-related streaming issue

Yes

### Android version

Android 15

### Device model

vivo x200 pro mini

### Server PC OS version

windows 11 IoT LTSC 24H2

**Comment by ClassicOldSong** [comment]
MTK设备本身幺蛾子就多，而且厂商优化可能还得过一阵子才能稳定

串流还是尽量选高通吧，我手上三台8G3体验都非常好
