### ISSUE TITLE
[Issue]: "Double Click Issue with Mouse on Mi Box S 2nd Generation"

### ISSUE THREAD

**Issue by Gustavo14832** [ClassicOldSong/moonlight-android#49]
### Describe the bug

The double click bug with the mouse is a native issue of the Mi Box itself. However, it would be beneficial to have a way through Artemis to resolve this problem, allowing users to utilize the mouse normally.

### Steps to reproduce

.

### Affected games

.

### Other Moonlight clients

None

### Moonlight adjusted settings

None

### Moonlight adjusted settings (please complete the following information)

.

### Moonlight default settings

Yes

### Gamepad-related connection issue

Yes

### Gamepad-related input issue

Yes

### Gamepad-related streaming issue

Yes

### Android version

Android 11

### Device model

Mi box s 2nd

### Server PC OS version

Windows 10

### Server PC GeForce Experience version

.

### Server PC Nvidia GPU driver version

538.46

### Server PC antivirus and firewall software

Windows defender

### Screenshots

.

### Relevant log output

```Shell
.
```

### Additional context

.

**Comment by ClassicOldSong** [comment]
I need a physical device to determine how the double click happens and if there's a way to resolve it.

It should be a bug report to Xiaomi but a feature request here.

**Comment by Gustavo14832** [comment]
From what I've been researching about why this happens, I got the answer that the mi box understands that clicking the left mouse button also means pressing the DPAD_CENTER on the remote control, causing 2 commands to be executed at the same time, xiaomi I should have fixed this error a long time ago but so far nothing has happened.

**Comment by ClassicOldSong** [comment]
Searching through the codebase I can't find any reference that mapped DPAD_CENTER to left click, I still need a physical device to test out the behavior...

**Comment by Gustavo14832** [comment]
After some time searching for possible solutions, I found a few alternatives that might solve the problem.

1. Add an option to change the recognition of a double-click.

2. An option to invert the mouse buttons, making the right one behave like the left. (Maybe this doesn't make much sense since Windows offers this option, but some Reddit users have solved their problems this way.)

3. After using Parsec on the Mi Box, I noticed that the double-click doesn't occur there, so there might be something that Parsec implemented that could solve my problem. (My guess would be the immersive mode)

**Comment by Gustavo14832** [comment]
Update!

After further research, I discovered that by using an app that disables the HOME button functionality, the mouse stops having issues, but in exchange, the remote control on the Mi Box stops working.

This is perfect for me, but up to a point, because now I’m facing another issue.

Even though the mouse works perfectly and clicks normally on the Windows desktop, when I enter any game, the camera becomes extremely sensitive.

Another thing is that now changing the mouse sensitivity in Windows itself no longer has any effect.

In a quick search, I saw that some users report the same issue in games using Steam Link.

If you have any idea what could be causing this, I would be extremely grateful if you could share it with me and, if possible, suggest any potential solutions.

**Comment by ClassicOldSong** [comment]
Is that app using an overlay or requires the permission for display over other apps?

**Comment by Gustavo14832** [comment]
Here is the translation to English:

The app didn't ask me for any special permissions; I just logged in and clicked the button to block the HOME button. If you want to see how it works, here is the GitHub repository: https://github.com/shaobin0604/Android-HomeKey-Locker

(Unfortunately, it is no longer available on the Play Store, but there are downloads available on the internet.)

**Comment by ClassicOldSong** [comment]
https://github.com/shaobin0604/Android-HomeKey-Locker/blob/master/HomeLockerLib/src/main/java/io/github/homelocker/lib/HomeKeyLocker.java#L24

It is actually creating an overlay. In this case, it's just like when you enabled "optimize for remote desktop usage instead of games" in Artemis's settings, as it's sending absolute coordinates of the mouse to applications underlaying when home button is locked instead of relative mouse movements. Games tend to read relative mouse movements from the center of the screen instead of absolute mouse coordinates for camera angle control, so it's behaving "way too sensitive" when mouse position is always updated in absolute coordinates.

**Comment by Gustavo14832** [comment]
Then, isn't there something to disable this overlay?

**Comment by ClassicOldSong** [comment]
If you disabled the overlay, the home button disable feature won't work either. It useing the overlay to intercept button presses.

**Comment by Gustavo14832** [comment]
I see, so the only way for it to work properly would be an immersive mode similar to Parsec's.

**Comment by ClassicOldSong** [comment]
Immersive mode couldn't solve the issue. Immersive mode is the same as full screen, Moonlight/Artemis already does this to hide status bar and navigation bar. They must have handled the situation specially for the device.

**Comment by Gustavo14832** [comment]
Unfortunately, a very good device like the Mi Box tends to be problematic in simple aspects like this mouse functionality, something that alternative devices can execute without issues. What’s left for me is to wait for a miraculous update that will fix this problem for good.

**Comment by ClassicOldSong** [comment]
Try this version https://github.com/ClassicOldSong/moonlight-android/releases/tag/v12.1.241203 , enable `Ignore Synth Events` and see if it works.

**Comment by Gustavo14832** [comment]
I went into the Artemis settings to enable the option, but I encountered a crash every time I click on the gear, something that didn't happen in the version I was using previously (v12.1-artemis-241120).

**Comment by Gustavo14832** [comment]
DUDE!!!

Through an APK editor, I was able to check the 'Ignore Synth Events' box and finally the error is 100% fixed, I’m jumping with joy lol

Even the menu is showing up now when I press the back button on the remote, which wasn’t happening before.

I can’t express in words how happy this is making me, thank you so much for the support with this issue that has been haunting me for a long time lol."

**Comment by ClassicOldSong** [comment]
> I went into the Artemis settings to enable the option, but I encountered a crash every time I click on the gear, something that didn't happen in the version I was using previously (v12.1-artemis-241120).

The latest version still crashes on the settings?

**Comment by Gustavo14832** [comment]
Yes

**Comment by ClassicOldSong** [comment]
Can you provide the logcat when it crashes?

**Comment by Gustavo14832** [comment]
I tried in several ways, but I didn't get any results to get a logcat.

**Comment by Gustavo14832** [comment]
The device only provides me with logcat related to its own operation.

**Comment by Gustavo14832** [comment]
And apparently, I celebrated too soon, lol.

The error is fixed because I hadn't activated the keyboard input, but when it's activated, the click error reappears. Here's the video for better understanding.

https://github.com/user-attachments/assets/25736e43-d70a-45a2-8362-c608828f057b

**Comment by ClassicOldSong** [comment]
So it's not double clicking, it's click + enter. Now I think konw where the problem actually is. Could you double check that by opening https://keycode.info/ , and click your mouse button on the page? It should tell you which key it just pressed.

**Comment by Gustavo14832** [comment]
Ah yes, sorry, it was a misunderstanding I had when saying it referred to a double click, because for a program to open, a double click is necessary lol.

**Comment by Gustavo14832** [comment]
![Captura de tela 2024-12-03 035333](https://github.com/user-attachments/assets/b11809c8-50b7-4b9e-97f5-c49b0383292e)

**Comment by ClassicOldSong** [comment]
Try this again: https://github.com/ClassicOldSong/moonlight-android/releases/tag/v12.1.241203-2

**Comment by Gustavo14832** [comment]
Well, the issue of crashing when entering the settings has been completely resolved, but now with the 'ignore synthetic events' option enabled, the mouse won't move, and its right button is being recognized as a back gesture, causing the advanced menu to open when clicked.

**Comment by Gustavo14832** [comment]
The "Esc" key on the keyboard also stops working when the option is enabled.

**Comment by ClassicOldSong** [comment]
🫠I'm out of ideas...

Guess I have to purchase one anyway...

**Comment by Gustavo14832** [comment]
I understand, but could you please revert to the way it was working in the previous version? It’s much better for the remote control of the device to be recognized to open the advanced menu.

**Comment by ClassicOldSong** [comment]
Disable the option reverts to the old behavior.

**Comment by Gustavo14832** [comment]
Even after disabling it, it's not working on the remote control like it did in the previous version, where pressing the back button would open the menu. This is only happening with the mouse now, as if the permission to do this has been transferred from the remote control to the mouse.

**Comment by Gustavo14832** [comment]
This even explains why the device is not recognizing the motion sensor of the mouse on the desktop, as it is interpreting that it only has buttons.

**Comment by ClassicOldSong** [comment]
Just bought a MiBOX 4C and couldn't reproduce the problem, mouse works and back menu/right click can be triggered correctly. It has another problem though, the mouse cannot be captured. The MiBOX S 2Gen is not selling in mainland China so I couldn't get one.
