### ISSUE TITLE
[Feature request]: add an option to choose a different button or combo to call Game back menu from controller, or disable the call from the pad

### ISSUE THREAD

**Issue by roob0** [ClassicOldSong/moonlight-android#5]
### Is your feature request related to a problem? Please describe.

When playing on tv mouse emulation mode triggered by start button is essential. But holding down the start button activates the Game back menu, and turn the mouse emulation off and on inside menu it's frustrating 

### Describe the solution you'd like

When playing on tv mouse emulation mode triggered by start button is essential. So, I think that  it would be better to disable the game back menu from controller's start button. Maybe it could be add an option to turn it off, or to choose another button or combo to trigger it.

### Describe alternatives you've considered

When playing on tv mouse emulation mode triggered by start button is essential. So, I think that  it would be better to disable the game back menu from controller's start button. Maybe it could be add an option to turn it off, or to choose another button or combo to trigger it.

**Comment by ClassicOldSong** [comment]
Fixed in https://github.com/ClassicOldSong/moonlight-android/releases/tag/v12.1-artemis-240818-2

Now long press should toggle mouse mode as usual, game back menu will be triggered with double tap and hold instead.

**Comment by roob0** [comment]
You're great!
