### ISSUE TITLE
[Feature request]: Improved Zoom/Pinch Configuration Persistence

### ISSUE THREAD

**Issue by dragaoazuljr** [ClassicOldSong/moonlight-android#50]
### Is your feature request related to a problem? Please describe.

I want to start by congratulating you on the fantastic application. I encountered numerous issues with the official Android app, most of which your fork has resolved. One issue is with the Zoom/Pinch functionality. Currently, as I use the app with Linux on sunhine server, I cannot create a virtual monitor (or set the current one) that matches my phone’s aspect ratio. As a workaround, I force the resolution using gamescope when launching a game, resulting in a stream with a letterbox effect. I then zoom in the client to fill the screen, which works fine, but it's tedious to do this every time I start a game.

### Describe the solution you'd like

I would like to suggest a way to persist the last applied zoom/pinch setting. Alternatively, when performing the zoom action, it could display a toast with the zoom calculation or value, allowing users to save this setting in the app’s configurations.

### Describe alternatives you've considered

I attempted to use the suggestion in the settings to set a custom resolution and enable stretch to fill the screen, but this approach conflicts with my gamescope setup. I need to initiate the stream with the resolution that will be displayed, as gamescope scales it accordingly when the game starts. If you have any other suggestions to help with this issue, I would greatly appreciate it. Thank you in advance!

**Comment by ClassicOldSong** [comment]
The user ergonomics for a presistent zoom/pan is hard to design.

Have you tried switching scaling mode to `Fill` and put your game in the center of your display? This might work with the letter boxing setup you have done.

**Comment by dragaoazuljr** [comment]
I understand. Fill I tried but only works when setting to a 16:9 resolution, but with that I cant force the ultra wide in the game. Other thing that is annoying is to disable the zoom/pan mode on a device without a physical back button, when trying to swipe to show the back button it always move the screen. Maybe can add a way to  show the back menu with a gamepad button combo? Like holding L3+R3.

**Comment by ClassicOldSong** [comment]
Actually there is. Tap once and then hold select for a while, release it, you can get the back menu shown.

If you're using fill mode you don't want to set the streaming resolution to your native resolution. That is because if your screen isn't the same aspect ratio as your streaming resolution, the black bar actually comes from the video stream itself. So there's no point to set native resolution if you're going to scale the view anyways.

**Comment by ClassicOldSong** [comment]
Is this issue still relevant?

**Comment by dragaoazuljr** [comment]
No, the solution you said really helped. I’ll close the issue.
