### ISSUE TITLE
[Issue]: 澎湃os2频繁无响应

### ISSUE THREAD

**Issue by jinbaix** [ClassicOldSong/moonlight-android#51]
### Describe the bug

安卓15 澎湃os2 10秒内弹出多次无响应
有录屏 可添加联系方式发送

### Steps to reproduce

必定触发

### Other Moonlight clients

None

### Moonlight adjusted settings

None

### Moonlight default settings

Yes

### Gamepad-related connection issue

No

### Gamepad-related input issue

Yes

### Gamepad-related streaming issue

Yes

### Android version

15

### Device model

小米pad6s pro

### Server PC OS version

win11

### Server PC antivirus and firewall software

无 默认的df

**Comment by ClassicOldSong** [comment]
录屏不能提供任何有效信息，小米瞎搞Android也不是一次两次的事情了

手机连上adb，logcat输出提供一下，直接用文件传issue输入框里就行

**Comment by ClassicOldSong** [comment]
我新入手的1+13是没这个问题的。所以请联系小米处理魔改导致的兼容性问题。
