### ISSUE TITLE
[Feature request]: multiple saved states for on screen controls 

### ISSUE THREAD

**Issue by onecamband** [ClassicOldSong/moonlight-android#53]
### Is your feature request related to a problem? Please describe.

I use a foldable phone and would like to customize a controller state for each screen and freely switch between them. This can also be useful if different layouts are needed for different games.

### Describe the solution you'd like

An option to save the current controller state and a menu option to switch between saved states. Also perhaps an option in settings to manage delete and name saves.

### Describe alternatives you've considered

I've tried using Artemis for the main screen and regular moonlight for the cover screen, but moonlight lacks features that I've grown to love since switching to Artemis, like the guide button, the full keyboard, and multi touch support

**Comment by ClassicOldSong** [comment]
There's already profile management in the settings, it's just not hot swappable in the stream for now.

I don't have a foldable phone so features realted to these won't be implemented and tested with high priority until I can afford one.

**Comment by ClassicOldSong** [comment]
Dup #43

**Comment by onecamband** [comment]
I see the profile management. However, this is for the "special keys" layout. What I'm referring to is the on-screen gamepad. The gamepad does not seem to be affected by profile changes and the only related option is to clear all saved data. It would be nice to not have to reset and recreate my layout every time I want to change my controls.

**Comment by ClassicOldSong** [comment]
I understand. They'll be handled all together in the future.
