### ISSUE TITLE
[Feature request]: 完善对触控板的支持

### ISSUE THREAD

**Issue by chr431** [ClassicOldSong/moonlight-android#55]
### Is your feature request related to a problem? Please describe.

我的设备是matepad pro 12.2英寸搭配原厂键盘，在使用触控板的时候发现了以下几个问题：
1.串流中触控板移动的分辨率似乎不高，且有很大的死区，导致串流中很难通过触控板来把鼠标指针移动到很小的按钮上
2.目前支持的触控板手势很少，如双指放大缩小，多指上滑返回桌面等功能均不支持。另外双指拖动有时候是反的，比如把指针放在滑块上，双指向左拖动，滑块会向右移动。

### Describe the solution you'd like

最迫切的需求是提高触控板移动的分辨率，目前由于移动过于不精确，串流使用如VS等有很多小按钮的软件效率比较低
我推测目前对触控板的支持应该是通过模拟鼠标来实现的，因此无法实现鼠标做不到的操作。Windows对触控版有原生支持，是否可以直接传输原生触控板事件？
另外，是否可以通过无障碍权限来接管触控板，实现在小窗模式下用触控板控制电脑鼠标指针？目前通过无障碍可以在小窗模式下用键盘控制电脑，如果触控板也可以使用，将会极大增强小窗模式的可用性

### Describe alternatives you've considered

或许可以在apollo里内置一个虚拟触控板，用于执行触控板传输的操作

**Comment by ClassicOldSong** [comment]
Windows不支持通过注入input事件的形式来模拟触摸板，唯一可行的方式是模拟HID/虚拟USB设备，而这两种操作都需要内核驱动，而内核驱动都不允许自签，除非打开测试模式，但有些反作弊会检测测试模式来防止DMA作弊之类的操作。

另外内核驱动实现起来也非常非常麻烦。

至于触摸板死区，这个是厂商的问题没办法解决，灵敏度的话目前设置里已经有灵敏度可以设置了，你可以提高一些试试看。

触摸板分辨率也不是app端可以解决的，这个是硬件限制。可以打开Windows鼠标设置里的 提高移动精确度 再看看会不会舒服一点。

滚动方向的话，触摸板绝大多数人都是自然滚动，因此直接按自然滚动实现了。

至于小窗模式，那个本来就是不响应任何输入的，平板系统原生应该有分屏/窗口模式，在这个情况下使用本地鼠标模式可以比较方便地跨屏幕使用鼠标。

**Comment by chr431** [comment]
> Windows不支持通过注入input事件的形式来模拟触摸板，唯一可行的方式是模拟HID/虚拟USB设备，而这两种操作都需要内核驱动，而内核驱动都不允许自签，除非打开测试模式，但有些反作弊会检测测试模式来防止DMA作弊之类的操作。
> 
> 另外内核驱动实现起来也非常非常麻烦。
> 
> 至于触摸板死区，这个是厂商的问题没办法解决，灵敏度的话目前设置里已经有灵敏度可以设置了，你可以提高一些试试看。
> 
> 触摸板分辨率也不是app端可以解决的，这个是硬件限制。可以打开Windows鼠标设置里的 提高移动精确度 再看看会不会舒服一点。
> 
> 滚动方向的话，触摸板绝大多数人都是自然滚动，因此直接按自然滚动实现了。
> 
> 至于小窗模式，那个本来就是不响应任何输入的，平板系统原生应该有分屏/窗口模式，在这个情况下使用本地鼠标模式可以比较方便地跨屏幕使用鼠标。

关于分辨率和死区我之前没有说清楚，触控板自身的硬件性能肯定是够用的，在安卓系统内使用触控板的时候并没有可感知的死区，分辨率也比较高，只是在串流的时候有问题。

**Comment by ClassicOldSong** [comment]
我自己1+平板是没这个问题的

很有可能是华为魔改以后传递给应用程序的分辨率不够高

建议USB直插鼠标使用，或者使用本地鼠标模式（勾选 为远程桌面而不是游戏优化）
