### ISSUE TITLE
[Issue]: Unable to access settings menu with Google TV Streamer

### ISSUE THREAD

**Issue by janiteee** [ClassicOldSong/moonlight-android#67]
### Describe the bug

Versions after v12.1-artemis-241120 won't let me access the setting menu with Google TV Streamer. The app just closes and returns to Google TV home page. In version v12.1-artemis-241120 setting menu work normally. 

### Steps to reproduce

Selecting setting cog icon causes the app to close. 

### Other Moonlight clients

None

### Moonlight adjusted settings

None

### Moonlight adjusted settings (please complete the following information)

All setting on their default values. 

### Moonlight default settings

Yes

### Gamepad-related connection issue

Yes

### Gamepad-related input issue

Yes

### Gamepad-related streaming issue

Yes

### Android version

Android 14 for TV's

### Device model

Google TV Streamer

### Server PC OS version

Windows 11 24H2

**Comment by ClassicOldSong** [comment]
Should have fixed in https://github.com/ClassicOldSong/moonlight-android/releases/tag/v12.1.241203

**Comment by andrewc12** [comment]
Didnt work https://github.com/user-attachments/assets/1d8fee90-912c-4afe-8fc4-8a6eaffdd3aa

![IMG_20241203_131719.jpg](https://github.com/user-attachments/assets/8b365474-cced-4939-a143-1f075709a69d)

**Comment by andrewc12** [comment]
Didnt work https://github.com/user-attachments/assets/1d8fee90-912c-4afe-8fc4-8a6eaffdd3aa
![IMG_20241203_131719.jpg](https://github.com/user-attachments/assets/e319db71-d582-4b64-8f89-79fa7108a7c2)

**Comment by ClassicOldSong** [comment]
Try this again: https://github.com/ClassicOldSong/moonlight-android/releases/tag/v12.1.241203-2

**Comment by andrewc12** [comment]
I'm using a different Android TV projector that had the same problem.
Seems to work now.
![IMG_20241203_202429.jpg](https://github.com/user-attachments/assets/0cf2f9cb-7cb0-4177-9522-684f10d5b826)
