### ISSUE TITLE
[Feature request]: Add an option to release sticky modifier keys after combination key is pressed

### ISSUE THREAD

**Issue by huyz-git** [ClassicOldSong/moonlight-android#7]
### Is your feature request related to a problem? Please describe.

Currently, when sticky modifier keys option is on, modifier keys will keep in pressed state until you press them again. This can sometimes be annoying.
For example, after I use `Ctrl+Alt+Shift+2` to switch screen, I have to press each `Ctrl` `Alt` `Shift` again to release them before I can do normal typing.

Most other keyboards I used is not this behavior. For example, IMEs like `gboard` and `fcitx5-android` will release the `Shift` key right after any alphabet key is pressed, and if you want to keep `Shift` key pressed, you need to double tap or long press it. On `termux`'s "extra-keys" keyboard, modifier keys will automatically release if you press them normally, and will not if you long press them.

### Describe the solution you'd like

It would be nice to add an option, which changes modifier keys' behavior to match IMEs or `termux`, i.e., automatically release modifier keys when pressed normally, and keep current behavior when double tapped or long pressed.

### Describe alternatives you've considered

Or, just add another option, when it's on, the sticky modifier keys will automatically release after other non-modifier keys is pressed.

**Comment by ClassicOldSong** [comment]
For more complex keyboard usage, would you please use Hacker's Keyboard? It's a more complete keyboard dedicated designed for programming purposes.

**Comment by ClassicOldSong** [comment]
Here I found an even better keyboard which you can customize the layout into the most suitable one for you: https://github.com/Julow/Unexpected-Keyboard

This project will focus on streaming part, so keyboard enhancement is not a priority at the moment.
