### ISSUE TITLE
Video stops decoding after change in activity on pc

### ISSUE THREAD

**Issue by andrewc12** [ClassicOldSong/moonlight-android#70]
### Describe the bug

Moonlight stops showing the video.
I am running software/Intel encoding over ethernet. 
I'm assuming the hardware decoder had an underun. 

If I increase the the resolution to 4k / framerate to 120fps and or set the latency to smooth, increasing the latency the problem occurs less often .

Doesn't occur on phone, tablet, or projector with android tv

### Steps to reproduce

Connect to PC, with 1080p 60fps videostream and low latency
Perform activities that change the complexity of the video increasing the data transfered. 

### Affected games

Desktop

### Other Moonlight clients

None

### Moonlight adjusted settings

None

### Moonlight adjusted settings (please complete the following information)

90 Mbps bitrate

### Gamepad-related connection issue

Yes

### Gamepad-related input issue

Yes

### Gamepad-related streaming issue

Yes

### Android version

11

### Device model

Hk1 box - kinhank super cube

### Server PC OS version

Windows 11 23H2

### Screenshots

https://photos.app.goo.gl/tUfwNUfk3Ro6nT8s7

**Comment by ClassicOldSong** [comment]
Random Aliexpress devices are not supported. They do not offer legit and stable software support, even their hardware specs are not open.

Also you can upload videos and photos directly with GitHub.

**Comment by ClassicOldSong** [comment]
One alternative, you can try EmuELEC on the box and use the Qt version of client. But still, no guarantee it will work and no support can be sourced from the manufaturer, that makes downstream software very hard to debug.

**Comment by andrewc12** [comment]
No problem.
What I was really meaning to ask but didn't actually ask was if it would be possible to add an option for buffering or some minimum latency.
But don't worry too hard about it, all I need to do is disconnect and reconnect.

**Comment by andrewc12** [comment]
This seems to not happen in the latest version using warp frame pacing.
There might be other reasons it's not happening though. I can't remember if I changed some other settings.

**Comment by ClassicOldSong** [comment]
Good to hear warp fixes so many things unexpectedly 😂

**Comment by andrewc12** [comment]
I was wrong. I had forced H.265. :(

**Comment by ClassicOldSong** [comment]
Still valuable information!
